/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Salon Booking API
 * API for Salon Booking Application
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface AdminServiceDto {
  /** @nullable */
  serviceName?: string | null;
  duration?: number;
  price?: number;
  isActive?: boolean;
  /** @nullable */
  salonName?: string | null;
}

export interface AdminServices {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  serviceName?: string | null;
  duration?: number;
  price?: number;
  isActive?: boolean;
  /** @nullable */
  salonName?: string | null;
}

export interface AdminServicesApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: AdminServices;
}

export interface AdminServicesListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: AdminServices[] | null;
}

export interface Booking {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  customerId?: string | null;
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  serviceId?: string | null;
  /** @nullable */
  salonName?: string | null;
  appointmentDate?: string;
  amount?: number;
  /** @nullable */
  status?: string | null;
}

export interface BookingApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: Booking;
}

export interface BookingDto {
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  serviceId?: string | null;
  appointmentDate?: string;
  /** @nullable */
  salonName?: string | null;
  amount?: number;
}

export interface BooleanApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: boolean;
}

export interface CompanyDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  status?: string | null;
}

export interface LoginRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

/**
 * @nullable
 */
export type ObjectApiResponseResult = unknown | null;

export interface ObjectApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: ObjectApiResponseResult;
}

export interface RegisterAdminRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}

export interface RegisterCustomerRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}

export interface RegisterEmployeeRequest {
  /** @nullable */
  staffId?: string | null;
}

export interface RegisterSuperAdminRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface Staff {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  password?: string | null;
  isActive?: boolean;
  joinedDate?: string;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  readonly phoneNumber?: string | null;
}

export interface StaffApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: Staff;
}

export interface StaffDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  role?: string | null;
  isActive?: boolean;
  joinedDate?: string;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  readonly phoneNumber?: string | null;
}

export interface StaffListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: Staff[] | null;
}

export interface StringApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: string | null;
}

export interface TimeDto {
  /** @nullable */
  day?: string | null;
  /** @nullable */
  opening?: string | null;
  /** @nullable */
  closing?: string | null;
  isOpen?: boolean;
}

export interface UpdateBookingStatusDto {
  /** @nullable */
  status?: string | null;
}

export interface UpdateUserRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  role?: number;
  isActive?: boolean;
}

export interface User {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  role?: UserRole;
  isActive?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  companyId?: string | null;
  /** @nullable */
  customerProfileId?: string | null;
  /** @nullable */
  employeeProfileId?: string | null;
}

export interface UserApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: User;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;

export type GetAllBookingParams = {
page?: number;
pageSize?: number;
};

export type GetAllStaffParams = {
page?: number;
pageSize?: number;
};

export type GetAllUsersParams = {
page?: number;
pageSize?: number;
};

export const getSalonBookingAPI = () => {
const getAllServices = <TData = AxiosResponse<AdminServicesListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices`,options
    );
  }

const createService = <TData = AxiosResponse<AdminServicesApiResponse>>(
    adminServiceDto: AdminServiceDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/AdminServices`,
      adminServiceDto,options
    );
  }

const getServiceById = <TData = AxiosResponse<AdminServicesApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices/${id}`,options
    );
  }

const updateService = <TData = AxiosResponse<AdminServicesApiResponse>>(
    id: string,
    adminServiceDto: AdminServiceDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/AdminServices/${id}`,
      adminServiceDto,options
    );
  }

const deleteService = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/AdminServices/${id}`,options
    );
  }

const getServicesBySalon = <TData = AxiosResponse<AdminServicesListApiResponse>>(
    salonName: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices/by-salon/${salonName}`,options
    );
  }

const getAllBooking = <TData = AxiosResponse<ObjectApiResponse>>(
    params?: GetAllBookingParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Booking`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const create = <TData = AxiosResponse<BookingApiResponse>>(
    bookingDto: BookingDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Booking`,
      bookingDto,options
    );
  }

const getById = <TData = AxiosResponse<BookingApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Booking/${id}`,options
    );
  }

const updateStatus = <TData = AxiosResponse<StringApiResponse>>(
    id: string,
    updateBookingStatusDto: UpdateBookingStatusDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Booking/${id}`,
      updateBookingStatusDto,options
    );
  }

const _delete = <TData = AxiosResponse<void>>(
    day: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Time/${day}`,options
    );
  }

const getAllCompanies = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Company`,options
    );
  }

const createCompany = <TData = AxiosResponse<void>>(
    companyDto: CompanyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Company`,
      companyDto,options
    );
  }

const getCompanyById = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Company/${id}`,options
    );
  }

const updateCompany = <TData = AxiosResponse<void>>(
    id: string,
    companyDto: CompanyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Company/${id}`,
      companyDto,options
    );
  }

const deleteCompany = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Company/${id}`,options
    );
  }

const mainB05 = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/`,options
    );
  }

const getAllStaff = <TData = AxiosResponse<ObjectApiResponse>>(
    params?: GetAllStaffParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const createStaff = <TData = AxiosResponse<StaffApiResponse>>(
    staffDto: NonReadonly<StaffDto>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Staff`,
      staffDto,options
    );
  }

const getStaffById = <TData = AxiosResponse<StaffApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff/${id}`,options
    );
  }

const updateStaff = <TData = AxiosResponse<StaffApiResponse>>(
    id: string,
    staffDto: NonReadonly<StaffDto>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Staff/${id}`,
      staffDto,options
    );
  }

const deleteStaff = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Staff/${id}`,options
    );
  }

const getStaffByRole = <TData = AxiosResponse<StaffListApiResponse>>(
    role: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff/role/${role}`,options
    );
  }

const getStaffBySalon = <TData = AxiosResponse<StaffListApiResponse>>(
    salonName: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff/salon/${salonName}`,options
    );
  }

const getActiveStaff = <TData = AxiosResponse<StaffListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff/active`,options
    );
  }

const getAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Time`,options
    );
  }

const createOrUpdate = <TData = AxiosResponse<void>>(
    timeDto: TimeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Time`,
      timeDto,options
    );
  }

const getByDay = <TData = AxiosResponse<void>>(
    day: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Time/${day}`,options
    );
  }

const update = <TData = AxiosResponse<void>>(
    day: string,
    timeDto: TimeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Time/${day}`,
      timeDto,options
    );
  }

const login = <TData = AxiosResponse<ObjectApiResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/login`,
      loginRequest,options
    );
  }

const registerCustomer = <TData = AxiosResponse<ObjectApiResponse>>(
    registerCustomerRequest: RegisterCustomerRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/customer`,
      registerCustomerRequest,options
    );
  }

const registerAdmin = <TData = AxiosResponse<ObjectApiResponse>>(
    registerAdminRequest: RegisterAdminRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/admin`,
      registerAdminRequest,options
    );
  }

const registerEmployee = <TData = AxiosResponse<ObjectApiResponse>>(
    registerEmployeeRequest: RegisterEmployeeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/employee`,
      registerEmployeeRequest,options
    );
  }

const registerSuperAdmin = <TData = AxiosResponse<ObjectApiResponse>>(
    registerSuperAdminRequest: RegisterSuperAdminRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/superadmin`,
      registerSuperAdminRequest,options
    );
  }

const getAllUsers = <TData = AxiosResponse<ObjectApiResponse>>(
    params?: GetAllUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/User`,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getUserById = <TData = AxiosResponse<UserApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/User/${id}`,options
    );
  }

const updateUser = <TData = AxiosResponse<StringApiResponse>>(
    id: string,
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/User/${id}`,
      updateUserRequest,options
    );
  }

const deleteUser = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/User/${id}`,options
    );
  }

return {getAllServices,createService,getServiceById,updateService,deleteService,getServicesBySalon,getAllBooking,create,getById,updateStatus,_delete,getAllCompanies,createCompany,getCompanyById,updateCompany,deleteCompany,mainB05,getAllStaff,createStaff,getStaffById,updateStaff,deleteStaff,getStaffByRole,getStaffBySalon,getActiveStaff,getAll,createOrUpdate,getByDay,update,login,registerCustomer,registerAdmin,registerEmployee,registerSuperAdmin,getAllUsers,getUserById,updateUser,deleteUser}};
export type GetAllServicesResult = AxiosResponse<AdminServicesListApiResponse>
export type CreateServiceResult = AxiosResponse<AdminServicesApiResponse>
export type GetServiceByIdResult = AxiosResponse<AdminServicesApiResponse>
export type UpdateServiceResult = AxiosResponse<AdminServicesApiResponse>
export type DeleteServiceResult = AxiosResponse<BooleanApiResponse>
export type GetServicesBySalonResult = AxiosResponse<AdminServicesListApiResponse>
export type GetAllBookingResult = AxiosResponse<ObjectApiResponse>
export type CreateResult = AxiosResponse<BookingApiResponse>
export type GetByIdResult = AxiosResponse<BookingApiResponse>
export type UpdateStatusResult = AxiosResponse<StringApiResponse>
export type _DeleteResult = AxiosResponse<void>
export type GetAllCompaniesResult = AxiosResponse<void>
export type CreateCompanyResult = AxiosResponse<void>
export type GetCompanyByIdResult = AxiosResponse<void>
export type UpdateCompanyResult = AxiosResponse<void>
export type DeleteCompanyResult = AxiosResponse<void>
export type MainB05Result = AxiosResponse<void>
export type GetAllStaffResult = AxiosResponse<ObjectApiResponse>
export type CreateStaffResult = AxiosResponse<StaffApiResponse>
export type GetStaffByIdResult = AxiosResponse<StaffApiResponse>
export type UpdateStaffResult = AxiosResponse<StaffApiResponse>
export type DeleteStaffResult = AxiosResponse<BooleanApiResponse>
export type GetStaffByRoleResult = AxiosResponse<StaffListApiResponse>
export type GetStaffBySalonResult = AxiosResponse<StaffListApiResponse>
export type GetActiveStaffResult = AxiosResponse<StaffListApiResponse>
export type GetAllResult = AxiosResponse<void>
export type CreateOrUpdateResult = AxiosResponse<void>
export type GetByDayResult = AxiosResponse<void>
export type UpdateResult = AxiosResponse<void>
export type LoginResult = AxiosResponse<ObjectApiResponse>
export type RegisterCustomerResult = AxiosResponse<ObjectApiResponse>
export type RegisterAdminResult = AxiosResponse<ObjectApiResponse>
export type RegisterEmployeeResult = AxiosResponse<ObjectApiResponse>
export type RegisterSuperAdminResult = AxiosResponse<ObjectApiResponse>
export type GetAllUsersResult = AxiosResponse<ObjectApiResponse>
export type GetUserByIdResult = AxiosResponse<UserApiResponse>
export type UpdateUserResult = AxiosResponse<StringApiResponse>
export type DeleteUserResult = AxiosResponse<BooleanApiResponse>
