/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Salon Booking API
 * API for Salon Booking Application
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface AdminServiceDto {
  /** @nullable */
  serviceName?: string | null;
  duration?: number;
  price?: number;
  isActive?: boolean;
  /** @nullable */
  salonName?: string | null;
}

export interface AdminServices {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  serviceName?: string | null;
  duration?: number;
  price?: number;
  isActive?: boolean;
  /** @nullable */
  salonName?: string | null;
}

export interface AdminServicesApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: AdminServices;
}

export interface AdminServicesListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: AdminServices[] | null;
}

export interface Booking {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  customerId?: string | null;
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  serviceId?: string | null;
  /** @nullable */
  salonName?: string | null;
  appointmentDate?: string;
  amount?: number;
  /** @nullable */
  status?: string | null;
}

export interface BookingApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: Booking;
}

export interface BookingDto {
  /** @nullable */
  staffId?: string | null;
  /** @nullable */
  serviceId?: string | null;
  appointmentDate?: string;
  /** @nullable */
  salonName?: string | null;
  amount?: number;
}

export interface BookingListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: Booking[] | null;
}

export interface BooleanApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: boolean;
}

export interface CompanyDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  status?: string | null;
}

export interface LoginRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

/**
 * @nullable
 */
export type ObjectApiResponseResult = unknown | null;

export interface ObjectApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: ObjectApiResponseResult;
}

export interface RegisterAdminRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}

export interface RegisterCustomerRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}

export interface RegisterEmployeeRequest {
  /** @nullable */
  staffId?: string | null;
}

export interface RegisterSuperAdminRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface Staff {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  password?: string | null;
  isActive?: boolean;
  joinedDate?: string;
  /** @nullable */
  salonName?: string | null;
}

export interface StaffApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: Staff;
}

export interface StaffDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  role?: string | null;
  isActive?: boolean;
  joinedDate?: string;
  /** @nullable */
  salonName?: string | null;
}

export interface StaffListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: Staff[] | null;
}

export interface StringApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: string | null;
}

export interface TimeDto {
  /** @nullable */
  day?: string | null;
  /** @nullable */
  opening?: string | null;
  /** @nullable */
  closing?: string | null;
  isOpen?: boolean;
}

export interface UpdateBookingStatusDto {
  /** @nullable */
  status?: string | null;
}

export interface UpdateUserRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  role?: number;
  isActive?: boolean;
}

export interface User {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  salonName?: string | null;
  /** @nullable */
  salonAddress?: string | null;
  role?: UserRole;
  isActive?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  companyId?: string | null;
  /** @nullable */
  customerProfileId?: string | null;
  /** @nullable */
  employeeProfileId?: string | null;
}

export interface UserApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  result?: User;
}

export interface UserListApiResponse {
  /** @nullable */
  message?: string | null;
  status?: boolean;
  /** @nullable */
  result?: User[] | null;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;

export const getSalonBookingAPI = () => {
const getApiAdminServices = <TData = AxiosResponse<AdminServicesListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices`,options
    );
  }

const postApiAdminServices = <TData = AxiosResponse<AdminServicesApiResponse>>(
    adminServiceDto: AdminServiceDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/AdminServices`,
      adminServiceDto,options
    );
  }

const getApiAdminServicesId = <TData = AxiosResponse<AdminServicesApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices/${id}`,options
    );
  }

const putApiAdminServicesId = <TData = AxiosResponse<AdminServicesApiResponse>>(
    id: string,
    adminServiceDto: AdminServiceDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/AdminServices/${id}`,
      adminServiceDto,options
    );
  }

const deleteApiAdminServicesId = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/AdminServices/${id}`,options
    );
  }

const getApiAdminServicesBySalonSalonName = <TData = AxiosResponse<AdminServicesListApiResponse>>(
    salonName: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/AdminServices/by-salon/${salonName}`,options
    );
  }

const getApiBooking = <TData = AxiosResponse<BookingListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Booking`,options
    );
  }

const postApiBooking = <TData = AxiosResponse<BookingApiResponse>>(
    bookingDto: BookingDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Booking`,
      bookingDto,options
    );
  }

const getApiBookingId = <TData = AxiosResponse<BookingApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Booking/${id}`,options
    );
  }

const putApiBookingId = <TData = AxiosResponse<StringApiResponse>>(
    id: string,
    updateBookingStatusDto: UpdateBookingStatusDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Booking/${id}`,
      updateBookingStatusDto,options
    );
  }

const deleteApiBookingId = <TData = AxiosResponse<StringApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Booking/${id}`,options
    );
  }

const getApiCompany = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Company`,options
    );
  }

const postApiCompany = <TData = AxiosResponse<void>>(
    companyDto: CompanyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Company`,
      companyDto,options
    );
  }

const getApiCompanyId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Company/${id}`,options
    );
  }

const putApiCompanyId = <TData = AxiosResponse<void>>(
    id: string,
    companyDto: CompanyDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Company/${id}`,
      companyDto,options
    );
  }

const deleteApiCompanyId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Company/${id}`,options
    );
  }

const get = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/`,options
    );
  }

const getApiStaff = <TData = AxiosResponse<StaffListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff`,options
    );
  }

const postApiStaff = <TData = AxiosResponse<StaffApiResponse>>(
    staffDto: StaffDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Staff`,
      staffDto,options
    );
  }

const getApiStaffId = <TData = AxiosResponse<StaffApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Staff/${id}`,options
    );
  }

const putApiStaffId = <TData = AxiosResponse<StaffApiResponse>>(
    id: string,
    staffDto: StaffDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Staff/${id}`,
      staffDto,options
    );
  }

const deleteApiStaffId = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Staff/${id}`,options
    );
  }

const getApiTime = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Time`,options
    );
  }

const postApiTime = <TData = AxiosResponse<void>>(
    timeDto: TimeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/Time`,
      timeDto,options
    );
  }

const getApiTimeDay = <TData = AxiosResponse<void>>(
    day: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/Time/${day}`,options
    );
  }

const putApiTimeDay = <TData = AxiosResponse<void>>(
    day: string,
    timeDto: TimeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/Time/${day}`,
      timeDto,options
    );
  }

const deleteApiTimeDay = <TData = AxiosResponse<void>>(
    day: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/Time/${day}`,options
    );
  }

const postApiUserLogin = <TData = AxiosResponse<ObjectApiResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/login`,
      loginRequest,options
    );
  }

const postApiUserRegisterCustomer = <TData = AxiosResponse<ObjectApiResponse>>(
    registerCustomerRequest: RegisterCustomerRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/customer`,
      registerCustomerRequest,options
    );
  }

const postApiUserRegisterAdmin = <TData = AxiosResponse<ObjectApiResponse>>(
    registerAdminRequest: RegisterAdminRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/admin`,
      registerAdminRequest,options
    );
  }

const postApiUserRegisterEmployee = <TData = AxiosResponse<ObjectApiResponse>>(
    registerEmployeeRequest: RegisterEmployeeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/employee`,
      registerEmployeeRequest,options
    );
  }

const postApiUserRegisterSuperadmin = <TData = AxiosResponse<ObjectApiResponse>>(
    registerSuperAdminRequest: RegisterSuperAdminRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:5296/api/User/register/superadmin`,
      registerSuperAdminRequest,options
    );
  }

const getApiUser = <TData = AxiosResponse<UserListApiResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/User`,options
    );
  }

const getApiUserId = <TData = AxiosResponse<UserApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:5296/api/User/${id}`,options
    );
  }

const putApiUserId = <TData = AxiosResponse<UserApiResponse>>(
    id: string,
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:5296/api/User/${id}`,
      updateUserRequest,options
    );
  }

const deleteApiUserId = <TData = AxiosResponse<BooleanApiResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:5296/api/User/${id}`,options
    );
  }

return {getApiAdminServices,postApiAdminServices,getApiAdminServicesId,putApiAdminServicesId,deleteApiAdminServicesId,getApiAdminServicesBySalonSalonName,getApiBooking,postApiBooking,getApiBookingId,putApiBookingId,deleteApiBookingId,getApiCompany,postApiCompany,getApiCompanyId,putApiCompanyId,deleteApiCompanyId,get,getApiStaff,postApiStaff,getApiStaffId,putApiStaffId,deleteApiStaffId,getApiTime,postApiTime,getApiTimeDay,putApiTimeDay,deleteApiTimeDay,postApiUserLogin,postApiUserRegisterCustomer,postApiUserRegisterAdmin,postApiUserRegisterEmployee,postApiUserRegisterSuperadmin,getApiUser,getApiUserId,putApiUserId,deleteApiUserId}};
export type GetApiAdminServicesResult = AxiosResponse<AdminServicesListApiResponse>
export type PostApiAdminServicesResult = AxiosResponse<AdminServicesApiResponse>
export type GetApiAdminServicesIdResult = AxiosResponse<AdminServicesApiResponse>
export type PutApiAdminServicesIdResult = AxiosResponse<AdminServicesApiResponse>
export type DeleteApiAdminServicesIdResult = AxiosResponse<BooleanApiResponse>
export type GetApiAdminServicesBySalonSalonNameResult = AxiosResponse<AdminServicesListApiResponse>
export type GetApiBookingResult = AxiosResponse<BookingListApiResponse>
export type PostApiBookingResult = AxiosResponse<BookingApiResponse>
export type GetApiBookingIdResult = AxiosResponse<BookingApiResponse>
export type PutApiBookingIdResult = AxiosResponse<StringApiResponse>
export type DeleteApiBookingIdResult = AxiosResponse<StringApiResponse>
export type GetApiCompanyResult = AxiosResponse<void>
export type PostApiCompanyResult = AxiosResponse<void>
export type GetApiCompanyIdResult = AxiosResponse<void>
export type PutApiCompanyIdResult = AxiosResponse<void>
export type DeleteApiCompanyIdResult = AxiosResponse<void>
export type GetResult = AxiosResponse<void>
export type GetApiStaffResult = AxiosResponse<StaffListApiResponse>
export type PostApiStaffResult = AxiosResponse<StaffApiResponse>
export type GetApiStaffIdResult = AxiosResponse<StaffApiResponse>
export type PutApiStaffIdResult = AxiosResponse<StaffApiResponse>
export type DeleteApiStaffIdResult = AxiosResponse<BooleanApiResponse>
export type GetApiTimeResult = AxiosResponse<void>
export type PostApiTimeResult = AxiosResponse<void>
export type GetApiTimeDayResult = AxiosResponse<void>
export type PutApiTimeDayResult = AxiosResponse<void>
export type DeleteApiTimeDayResult = AxiosResponse<void>
export type PostApiUserLoginResult = AxiosResponse<ObjectApiResponse>
export type PostApiUserRegisterCustomerResult = AxiosResponse<ObjectApiResponse>
export type PostApiUserRegisterAdminResult = AxiosResponse<ObjectApiResponse>
export type PostApiUserRegisterEmployeeResult = AxiosResponse<ObjectApiResponse>
export type PostApiUserRegisterSuperadminResult = AxiosResponse<ObjectApiResponse>
export type GetApiUserResult = AxiosResponse<UserListApiResponse>
export type GetApiUserIdResult = AxiosResponse<UserApiResponse>
export type PutApiUserIdResult = AxiosResponse<UserApiResponse>
export type DeleteApiUserIdResult = AxiosResponse<BooleanApiResponse>
